@baseUrl = http://localhost:8081
@contentType = application/json
@token = eyJhbGciOiJIUzI1NiIsInR...

### Listar todos los maniquíes
GET {{baseUrl}}/maniquies
Authorization: Bearer {{token}}

### Ensamblar nuevo Maniquí (SP EnsamblarManiqui)
POST {{baseUrl}}/maniquies
Authorization: Bearer {{token}}
Content-Type: {{contentType}}

{
  "modelo_id": 1,
  "numero_serie": "MQ-TEST-{{$timestamp}}",
  "numero_lote": "LOTE-001"
}

### Ver detalle de un Maniquí
GET {{baseUrl}}/maniquies/S-1
Authorization: Bearer {{token}}
